services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: falcon-app
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]
    restart: on-failure

volumes:
  pgdata:
