"""Add age for pets and users

Revision ID: fb6fe0829b67
Revises: 33e1a4e43852
Create Date: 2025-02-12 22:04:43.159249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6fe0829b67'
down_revision: Union[str, None] = '33e1a4e43852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('age', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pets_age'), 'pets', ['age'], unique=False)
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_column('users', 'age')
    op.drop_index(op.f('ix_pets_age'), table_name='pets')
    op.drop_column('pets', 'age')
    # ### end Alembic commands ###
