name: Run Tests with Docker and Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Docker Compose services
      run: docker-compose -f docker-compose.yml up -d db

    - name: Check if app container is running
      run: docker-compose ps

    - name: Check pytest version with verbosity
      run: docker-compose exec app pytest --version -v

    - name: Install pytest inside app container
      run: docker-compose exec app pip install pytest

    - name: Run tests with verbosity
      run: docker-compose exec app pytest spec --maxfail=5 --disable-warnings -v

    - name: Stop and remove containers
      run: docker-compose down
