name: Run tests with Docker and Database

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Docker Compose services
      run: |
        docker-compose -f docker-compose.yml up -d db  # Inicializa o banco de dados

    - name: Run tests
      run: |
        docker-compose exec app pytest spec

    - name: Stop and remove containers
      run: docker-compose down