name: Run Tests with Docker and Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Docker Compose services
      run: docker-compose -f docker-compose.yml up -d db

    - name: Install pytest inside app container
      run: docker-compose exec -T app pip install pytest

    - name: Wait for db service to initialize
      run: |
        docker-compose exec -T app bash -c "until nc -z db 5432; do echo 'Waiting for database connection...'; sleep 5; done"

    - name: Check pytest version with verbosity
      run: docker-compose exec -T app pytest --version -v

    - name: Run tests with verbosity
      run: docker-compose exec -T app pytest spec --maxfail=5 --disable-warnings -v

    - name: Stop and remove containers
      run: docker-compose
